apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployement
  labels:
    tier: forntend       
    app: nginx
spec:
  selector:
    matchLabels:
       app: myapp
  replicas: 3
  template:
      metadata:
        name: nginx
        labels:
             app: myapp
      spec:
          containers:
              - name: nginx
                image: nginx
        
 
